# Generated by Django 4.0 on 2021-12-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.URLField(blank=True, null=True)),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('season', models.ManyToManyField(related_name='ingredients', to='food.Season')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.unit')),
            ],
        ),
    ]
