# Generated by Django 4.0 on 2021-12-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_season_season_seasons_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='seasons',
            new_name='season',
        ),
    ]
