# Generated by Django 4.0 on 2021-12-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_seasons_season_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='name',
        ),
    ]
