# Generated by Django 4.0 on 2021-12-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_ingredient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
