# Generated by Django 4.0 on 2022-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='todo',
            field=models.BooleanField(default=False),
        ),
    ]
