# Generated by Django 4.0 on 2022-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
