# Generated by Django 4.0 on 2022-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_alter_shopping_list_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ailse',
            field=models.ManyToManyField(related_name='ingredients_in_ailse', to='food.Aisle'),
        ),
    ]
