# Generated by Django 4.0 on 2022-01-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_aisle_ingredient_ailse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='season',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='recipe',
            name='doable',
            field=models.BooleanField(default=False),
        ),
    ]
