# Generated by Django 4.0 on 2022-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_ingredient_season_remove_ingredient_vegan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='doable',
            field=models.BooleanField(default=True),
        ),
    ]
