# Generated by Django 4.0 on 2022-01-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_recipe_doable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='doable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredient'),
        ),
    ]
