# Generated by Django 4.0 on 2022-01-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_alter_recipe_doable_alter_stock_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredient'),
        ),
    ]
