# Generated by Django 4.0 on 2022-01-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_alter_shopping_list_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_planned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
