# Generated by Django 4.0 on 2022-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_stock_quantity_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_planned',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
